version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "3333:3333"
    volumes:
      - ./code/backend:/backend
    command: >
      sh -c "yarn dev"
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./code/frontend:/frontend
    command: >
      sh -c "yarn start"
    depends_on:
      - backend